#docker compose for mongodb and mongo express web ui
#NOTE: .mongo.env and .mongo-express.env files should be in the same directory as this file

services:

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    env_file:
      - .mongo.env

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    env_file:
      - .mongo-express.env